/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/hyperspaces-0.3.0-py3.6.egg/hyperspace/space/skopt/space.py:173: UserWarning: Each hyperspace contains a single value.
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/hyperspaces-0.3.0-py3.6.egg/hyperspace/space/skopt/space.py:173: UserWarning: Each hyperspace contains a single value.
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/hyperspaces-0.3.0-py3.6.egg/hyperspace/space/skopt/space.py:173: UserWarning: Each hyperspace contains a single value.
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/hyperspaces-0.3.0-py3.6.egg/hyperspace/space/skopt/space.py:173: UserWarning: Each hyperspace contains a single value.
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/hyperspaces-0.3.0-py3.6.egg/hyperspace/space/skopt/space.py:173: UserWarning: Each hyperspace contains a single value.
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/hyperspaces-0.3.0-py3.6.egg/hyperspace/space/skopt/space.py:173: UserWarning: Each hyperspace contains a single value.
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/hyperspaces-0.3.0-py3.6.egg/hyperspace/space/skopt/space.py:173: UserWarning: Each hyperspace contains a single value.
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/hyperspaces-0.3.0-py3.6.egg/hyperspace/space/skopt/space.py:173: UserWarning: Each hyperspace contains a single value.
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/hyperspaces-0.3.0-py3.6.egg/hyperspace/space/skopt/space.py:173: UserWarning: Each hyperspace contains a single value.
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/hyperspaces-0.3.0-py3.6.egg/hyperspace/space/skopt/space.py:173: UserWarning: Each hyperspace contains a single value.
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/hyperspaces-0.3.0-py3.6.egg/hyperspace/space/skopt/space.py:173: UserWarning: Each hyperspace contains a single value.
/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/hyperspaces-0.3.0-py3.6.egg/hyperspace/space/skopt/space.py:173: UserWarning: Each hyperspace contains a single value.
2019-03-27 13:41:31.574524: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-03-27 13:41:31.574524: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-03-27 13:41:31.574524: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-03-27 13:41:31.575110: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-03-27 13:41:31.575110: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-03-27 13:41:31.575110: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-03-27 13:41:31.600670: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-03-27 13:41:31.600670: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-03-27 13:41:31.600670: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-03-27 13:41:31.601068: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-03-27 13:41:31.601064: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-03-27 13:41:31.601063: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-03-27 13:41:36.950765: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-03-27 13:41:36.950859: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1467] Found device 0 with properties: 
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0004:05:00.0
totalMemory: 15.75GiB freeMemory: 15.34GiB
2019-03-27 13:41:36.950885: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1546] Adding visible gpu devices: 1
2019-03-27 13:41:36.950928: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.9.2
2019-03-27 13:41:36.951311: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-03-27 13:41:36.951388: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1467] Found device 0 with properties: 
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0035:03:00.0
totalMemory: 15.75GiB freeMemory: 15.34GiB
2019-03-27 13:41:36.951409: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1546] Adding visible gpu devices: 3
2019-03-27 13:41:36.951447: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.9.2
2019-03-27 13:41:36.954444: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-03-27 13:41:36.954532: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1467] Found device 0 with properties: 
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0004:04:00.0
totalMemory: 15.75GiB freeMemory: 15.34GiB
2019-03-27 13:41:36.954559: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1546] Adding visible gpu devices: 0
2019-03-27 13:41:36.954607: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.9.2
2019-03-27 13:41:36.956033: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-03-27 13:41:36.956122: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1467] Found device 0 with properties: 
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0004:06:00.0
totalMemory: 15.75GiB freeMemory: 15.34GiB
2019-03-27 13:41:36.956149: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1546] Adding visible gpu devices: 2
2019-03-27 13:41:36.956194: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.9.2
2019-03-27 13:41:36.958587: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-03-27 13:41:36.958649: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1467] Found device 0 with properties: 
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0035:04:00.0
totalMemory: 15.75GiB freeMemory: 15.34GiB
2019-03-27 13:41:36.958666: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1546] Adding visible gpu devices: 4
2019-03-27 13:41:36.958704: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.9.2
2019-03-27 13:41:36.959913: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-03-27 13:41:36.959989: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1467] Found device 0 with properties: 
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0035:05:00.0
totalMemory: 15.75GiB freeMemory: 15.34GiB
2019-03-27 13:41:36.960014: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1546] Adding visible gpu devices: 5
2019-03-27 13:41:36.960059: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.9.2
2019-03-27 13:41:36.962271: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-03-27 13:41:36.962382: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1467] Found device 0 with properties: 
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0004:05:00.0
totalMemory: 15.75GiB freeMemory: 15.34GiB
2019-03-27 13:41:36.962407: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1546] Adding visible gpu devices: 1
2019-03-27 13:41:36.962447: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.9.2
2019-03-27 13:41:36.962627: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-03-27 13:41:36.962687: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1467] Found device 0 with properties: 
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0004:06:00.0
totalMemory: 15.75GiB freeMemory: 15.34GiB
2019-03-27 13:41:36.962705: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1546] Adding visible gpu devices: 2
2019-03-27 13:41:36.962743: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.9.2
2019-03-27 13:41:36.967536: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-03-27 13:41:36.967616: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1467] Found device 0 with properties: 
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0004:04:00.0
totalMemory: 15.75GiB freeMemory: 15.34GiB
2019-03-27 13:41:36.967642: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1546] Adding visible gpu devices: 0
2019-03-27 13:41:36.967688: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.9.2
2019-03-27 13:41:36.970845: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-03-27 13:41:36.970917: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1467] Found device 0 with properties: 
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0035:04:00.0
totalMemory: 15.75GiB freeMemory: 15.34GiB
2019-03-27 13:41:36.970939: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1546] Adding visible gpu devices: 4
2019-03-27 13:41:36.970977: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.9.2
2019-03-27 13:41:36.971187: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-03-27 13:41:36.971246: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1467] Found device 0 with properties: 
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0035:05:00.0
totalMemory: 15.75GiB freeMemory: 15.34GiB
2019-03-27 13:41:36.971271: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1546] Adding visible gpu devices: 5
2019-03-27 13:41:36.971318: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.9.2
2019-03-27 13:41:36.971457: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-03-27 13:41:36.971549: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1467] Found device 0 with properties: 
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0035:03:00.0
totalMemory: 15.75GiB freeMemory: 15.34GiB
2019-03-27 13:41:36.971576: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1546] Adding visible gpu devices: 3
2019-03-27 13:41:36.971628: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.9.2
2019-03-27 13:41:37.478612: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1015] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-27 13:41:37.478656: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1021]      3 
2019-03-27 13:41:37.478668: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1034] 3:   N 
2019-03-27 13:41:37.479427: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1149] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14821 MB memory) -> physical GPU (device: 3, name: Tesla V100-SXM2-16GB, pci bus id: 0035:03:00.0, compute capability: 7.0)
2019-03-27 13:41:37.512003: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1015] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-27 13:41:37.512064: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1021]      1 
2019-03-27 13:41:37.512079: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1034] 1:   N 
2019-03-27 13:41:37.512915: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1149] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14821 MB memory) -> physical GPU (device: 1, name: Tesla V100-SXM2-16GB, pci bus id: 0004:05:00.0, compute capability: 7.0)
2019-03-27 13:41:37.553448: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1015] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-27 13:41:37.553512: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1021]      1 
2019-03-27 13:41:37.553528: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1034] 1:   N 
2019-03-27 13:41:37.554213: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1149] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14821 MB memory) -> physical GPU (device: 1, name: Tesla V100-SXM2-16GB, pci bus id: 0004:05:00.0, compute capability: 7.0)
2019-03-27 13:41:37.581380: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1015] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-27 13:41:37.581440: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1021]      4 
2019-03-27 13:41:37.581455: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1034] 4:   N 
2019-03-27 13:41:37.582161: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1149] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14823 MB memory) -> physical GPU (device: 4, name: Tesla V100-SXM2-16GB, pci bus id: 0035:04:00.0, compute capability: 7.0)
2019-03-27 13:41:37.592350: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1015] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-27 13:41:37.592391: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1021]      0 
2019-03-27 13:41:37.592406: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1034] 0:   N 
2019-03-27 13:41:37.593074: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1149] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14821 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0004:04:00.0, compute capability: 7.0)
2019-03-27 13:41:37.592968: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1015] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-27 13:41:37.593004: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1021]      0 
2019-03-27 13:41:37.593014: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1034] 0:   N 
2019-03-27 13:41:37.593632: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1149] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14821 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0004:04:00.0, compute capability: 7.0)
2019-03-27 13:41:37.595969: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1015] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-27 13:41:37.596004: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1021]      2 
2019-03-27 13:41:37.596018: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1034] 2:   N 
2019-03-27 13:41:37.596653: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1149] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14821 MB memory) -> physical GPU (device: 2, name: Tesla V100-SXM2-16GB, pci bus id: 0004:06:00.0, compute capability: 7.0)
2019-03-27 13:41:37.598955: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1015] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-27 13:41:37.598981: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1021]      2 
2019-03-27 13:41:37.598991: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1034] 2:   N 
2019-03-27 13:41:37.599605: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1149] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14821 MB memory) -> physical GPU (device: 2, name: Tesla V100-SXM2-16GB, pci bus id: 0004:06:00.0, compute capability: 7.0)
2019-03-27 13:41:37.610855: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1015] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-27 13:41:37.610901: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1021]      5 
2019-03-27 13:41:37.610915: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1034] 5:   N 
2019-03-27 13:41:37.611576: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1149] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14827 MB memory) -> physical GPU (device: 5, name: Tesla V100-SXM2-16GB, pci bus id: 0035:05:00.0, compute capability: 7.0)
2019-03-27 13:41:37.615380: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1015] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-27 13:41:37.615416: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1021]      3 
2019-03-27 13:41:37.615427: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1034] 3:   N 
2019-03-27 13:41:37.615982: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1149] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14823 MB memory) -> physical GPU (device: 3, name: Tesla V100-SXM2-16GB, pci bus id: 0035:03:00.0, compute capability: 7.0)
2019-03-27 13:41:37.640420: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1015] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-27 13:41:37.640471: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1021]      4 
2019-03-27 13:41:37.640485: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1034] 4:   N 
2019-03-27 13:41:37.641167: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1149] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14825 MB memory) -> physical GPU (device: 4, name: Tesla V100-SXM2-16GB, pci bus id: 0035:04:00.0, compute capability: 7.0)
2019-03-27 13:41:37.650987: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1015] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-27 13:41:37.651019: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1021]      5 
2019-03-27 13:41:37.651032: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1034] 5:   N 
2019-03-27 13:41:37.651698: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1149] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14821 MB memory) -> physical GPU (device: 5, name: Tesla V100-SXM2-16GB, pci bus id: 0035:05:00.0, compute capability: 7.0)
2019-03-27 13:41:41.663333: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.9.2
2019-03-27 13:41:42.431562: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.9.2
2019-03-27 13:41:42.999101: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.9.2
2019-03-27 13:41:43.340316: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.9.2
2019-03-27 13:41:43.468674: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.9.2
2019-03-27 13:41:43.517531: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.9.2
2019-03-27 13:41:43.528720: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.9.2
2019-03-27 13:41:43.568049: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.9.2
2019-03-27 13:41:43.603039: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.9.2
2019-03-27 13:41:43.634546: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.9.2
2019-03-27 13:41:43.707702: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.9.2
2019-03-27 13:41:53.984007: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.9.2
2019-03-27 13:41:57.863137: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-03-27 13:41:57.946755: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-03-27 13:41:57.997425: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-03-27 13:41:58.102882: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-03-27 13:41:58.198776: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-03-27 13:41:58.242973: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-03-27 13:41:58.243762: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-03-27 13:41:58.243896: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-03-27 13:41:58.249703: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-03-27 13:41:58.265144: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-03-27 13:41:58.583181: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-03-27 13:41:58.635200: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
Traceback (most recent call last):
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 527, in _apply_op_helper
Traceback (most recent call last):
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 527, in _apply_op_helper
Traceback (most recent call last):
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 527, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1186, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 2167, in _TensorConversionFunction
    "of type '%s'" % (dtype.name, v.dtype.name))
ValueError: Incompatible type conversion requested to type 'float16' for variable of type 'float32_ref'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "stemdl_run.py", line 276, in <module>
    main()
  File "stemdl_run.py", line 252, in main
    FLAGS
  File "../hspace/hyperspace_launcher.py", line 60, in run_hyperspace
    random_state=777
  File "/gpfs/alpine/lrn001/proj-shared/yngtodd/src/scikit-optimize/skopt/optimizer/gp.py", line 228, in gp_minimize
Traceback (most recent call last):
    callback=callback, n_jobs=n_jobs)
  File "/gpfs/alpine/lrn001/proj-shared/yngtodd/src/scikit-optimize/skopt/optimizer/base.py", line 240, in base_minimize
    y0 = list(map(func, x0))
  File "../hspace/hyperspace_launcher.py", line 51, in <lambda>
    params
  File "../hspace/medium_objective.py", line 42, in objective
    train_loss = runtime.train(network_config, hyper_params, params, hyper_optimization=True)
  File "../stemdl/runtime.py", line 374, in train
    validate(network_config, hyper_params, params, sess, dset)
  File "../stemdl/runtime.py", line 439, in validate
    n_net.build_model()
  File "../stemdl/network.py", line 965, in build_model
    preferred_dtype=default_dtype)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1186, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 2167, in _TensorConversionFunction
    "of type '%s'" % (dtype.name, v.dtype.name))
ValueError: Incompatible type conversion requested to type 'float16' for variable of type 'float32_ref'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "stemdl_run.py", line 276, in <module>
    main()
  File "stemdl_run.py", line 252, in main
    FLAGS
  File "../hspace/hyperspace_launcher.py", line 60, in run_hyperspace
    random_state=777
  File "/gpfs/alpine/lrn001/proj-shared/yngtodd/src/scikit-optimize/skopt/optimizer/gp.py", line 228, in gp_minimize
    callback=callback, n_jobs=n_jobs)
  File "/gpfs/alpine/lrn001/proj-shared/yngtodd/src/scikit-optimize/skopt/optimizer/base.py", line 240, in base_minimize
    y0 = list(map(func, x0))
  File "../hspace/hyperspace_launcher.py", line 51, in <lambda>
    params
  File "../hspace/medium_objective.py", line 42, in objective
    train_loss = runtime.train(network_config, hyper_params, params, hyper_optimization=True)
  File "../stemdl/runtime.py", line 374, in train
    validate(network_config, hyper_params, params, sess, dset)
  File "../stemdl/runtime.py", line 439, in validate
    n_net.build_model()
  File "../stemdl/network.py", line 965, in build_model
    out, kernel = self._conv(input=self.images, params=layer_params)
  File "../stemdl/network.py", line 378, in _conv
    out, kernel = self._conv(input=self.images, params=layer_params)
  File "../stemdl/network.py", line 378, in _conv
    output = tf.nn.conv2d(input, kernel, stride_shape, data_format='NCHW', padding=params['padding'])
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1951, in conv2d
    output = tf.nn.conv2d(input, kernel, stride_shape, data_format='NCHW', padding=params['padding'])
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1951, in conv2d
Traceback (most recent call last):
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 527, in _apply_op_helper
    name=name)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1071, in conv2d
    name=name)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 563, in _apply_op_helper
    data_format=data_format, dilations=dilations, name=name)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 563, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'filter' of 'Conv2D' Op has type float32 that does not match type float16 of argument 'input'.
    inferred_from[input_arg.type_attr]))
TypeError: Input 'filter' of 'Conv2D' Op has type float32 that does not match type float16 of argument 'input'.
Traceback (most recent call last):
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 527, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1186, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 2167, in _TensorConversionFunction
    "of type '%s'" % (dtype.name, v.dtype.name))
ValueError: Incompatible type conversion requested to type 'float16' for variable of type 'float32_ref'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "stemdl_run.py", line 276, in <module>
    main()
  File "stemdl_run.py", line 252, in main
    FLAGS
  File "../hspace/hyperspace_launcher.py", line 60, in run_hyperspace
    random_state=777
  File "/gpfs/alpine/lrn001/proj-shared/yngtodd/src/scikit-optimize/skopt/optimizer/gp.py", line 228, in gp_minimize
    callback=callback, n_jobs=n_jobs)
  File "/gpfs/alpine/lrn001/proj-shared/yngtodd/src/scikit-optimize/skopt/optimizer/base.py", line 240, in base_minimize
    y0 = list(map(func, x0))
  File "../hspace/hyperspace_launcher.py", line 51, in <lambda>
    params
  File "../hspace/medium_objective.py", line 42, in objective
    train_loss = runtime.train(network_config, hyper_params, params, hyper_optimization=True)
  File "../stemdl/runtime.py", line 374, in train
    validate(network_config, hyper_params, params, sess, dset)
  File "../stemdl/runtime.py", line 439, in validate
    n_net.build_model()
  File "../stemdl/network.py", line 965, in build_model
    out, kernel = self._conv(input=self.images, params=layer_params)
  File "../stemdl/network.py", line 378, in _conv
    output = tf.nn.conv2d(input, kernel, stride_shape, data_format='NCHW', padding=params['padding'])
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1951, in conv2d
    name=name)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 563, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'filter' of 'Conv2D' Op has type float32 that does not match type float16 of argument 'input'.
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 527, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1186, in internal_convert_to_tensor
    preferred_dtype=default_dtype)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1186, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 2167, in _TensorConversionFunction
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 2167, in _TensorConversionFunction
    "of type '%s'" % (dtype.name, v.dtype.name))
ValueError: Incompatible type conversion requested to type 'float16' for variable of type 'float32_ref'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "stemdl_run.py", line 276, in <module>
    "of type '%s'" % (dtype.name, v.dtype.name))
ValueError: Incompatible type conversion requested to type 'float16' for variable of type 'float32_ref'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "stemdl_run.py", line 276, in <module>
    main()
  File "stemdl_run.py", line 252, in main
    main()
  File "stemdl_run.py", line 252, in main
    FLAGS
  File "../hspace/hyperspace_launcher.py", line 60, in run_hyperspace
    FLAGS
  File "../hspace/hyperspace_launcher.py", line 60, in run_hyperspace
    random_state=777
  File "/gpfs/alpine/lrn001/proj-shared/yngtodd/src/scikit-optimize/skopt/optimizer/gp.py", line 228, in gp_minimize
    random_state=777
  File "/gpfs/alpine/lrn001/proj-shared/yngtodd/src/scikit-optimize/skopt/optimizer/gp.py", line 228, in gp_minimize
    callback=callback, n_jobs=n_jobs)
  File "/gpfs/alpine/lrn001/proj-shared/yngtodd/src/scikit-optimize/skopt/optimizer/base.py", line 240, in base_minimize
    y0 = list(map(func, x0))
  File "../hspace/hyperspace_launcher.py", line 51, in <lambda>
    callback=callback, n_jobs=n_jobs)
  File "/gpfs/alpine/lrn001/proj-shared/yngtodd/src/scikit-optimize/skopt/optimizer/base.py", line 240, in base_minimize
    y0 = list(map(func, x0))
  File "../hspace/hyperspace_launcher.py", line 51, in <lambda>
    params
  File "../hspace/medium_objective.py", line 42, in objective
    params
  File "../hspace/medium_objective.py", line 42, in objective
    train_loss = runtime.train(network_config, hyper_params, params, hyper_optimization=True)
  File "../stemdl/runtime.py", line 374, in train
    train_loss = runtime.train(network_config, hyper_params, params, hyper_optimization=True)
  File "../stemdl/runtime.py", line 374, in train
    validate(network_config, hyper_params, params, sess, dset)
  File "../stemdl/runtime.py", line 439, in validate
    validate(network_config, hyper_params, params, sess, dset)
  File "../stemdl/runtime.py", line 439, in validate
    n_net.build_model()
  File "../stemdl/network.py", line 965, in build_model
    n_net.build_model()
  File "../stemdl/network.py", line 965, in build_model
    out, kernel = self._conv(input=self.images, params=layer_params)
  File "../stemdl/network.py", line 378, in _conv
    out, kernel = self._conv(input=self.images, params=layer_params)
  File "../stemdl/network.py", line 378, in _conv
    output = tf.nn.conv2d(input, kernel, stride_shape, data_format='NCHW', padding=params['padding'])
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1951, in conv2d
    output = tf.nn.conv2d(input, kernel, stride_shape, data_format='NCHW', padding=params['padding'])
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1951, in conv2d
    name=name)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1071, in conv2d
    name=name)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 563, in _apply_op_helper
    data_format=data_format, dilations=dilations, name=name)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 563, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'filter' of 'Conv2D' Op has type float32 that does not match type float16 of argument 'input'.
    inferred_from[input_arg.type_attr]))
TypeError: Input 'filter' of 'Conv2D' Op has type float32 that does not match type float16 of argument 'input'.
Traceback (most recent call last):
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 527, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1186, in internal_convert_to_tensor
2019-03-27 14:13:47.530566: W tensorflow/core/kernels/data/generator_dataset_op.cc:79] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 2167, in _TensorConversionFunction
2019-03-27 14:13:47.531168: W tensorflow/core/kernels/data/generator_dataset_op.cc:79] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
    "of type '%s'" % (dtype.name, v.dtype.name))
ValueError: Incompatible type conversion requested to type 'float16' for variable of type 'float32_ref'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "stemdl_run.py", line 276, in <module>
    main()
  File "stemdl_run.py", line 252, in main
    FLAGS
  File "../hspace/hyperspace_launcher.py", line 60, in run_hyperspace
    random_state=777
  File "/gpfs/alpine/lrn001/proj-shared/yngtodd/src/scikit-optimize/skopt/optimizer/gp.py", line 228, in gp_minimize
    callback=callback, n_jobs=n_jobs)
  File "/gpfs/alpine/lrn001/proj-shared/yngtodd/src/scikit-optimize/skopt/optimizer/base.py", line 240, in base_minimize
    y0 = list(map(func, x0))
  File "../hspace/hyperspace_launcher.py", line 51, in <lambda>
    params
  File "../hspace/medium_objective.py", line 42, in objective
    train_loss = runtime.train(network_config, hyper_params, params, hyper_optimization=True)
  File "../stemdl/runtime.py", line 374, in train
    validate(network_config, hyper_params, params, sess, dset)
  File "../stemdl/runtime.py", line 439, in validate
    n_net.build_model()
  File "../stemdl/network.py", line 965, in build_model
    out, kernel = self._conv(input=self.images, params=layer_params)
  File "../stemdl/network.py", line 378, in _conv
    output = tf.nn.conv2d(input, kernel, stride_shape, data_format='NCHW', padding=params['padding'])
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1951, in conv2d
    name=name)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 563, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'filter' of 'Conv2D' Op has type float32 that does not match type float16 of argument 'input'.
Traceback (most recent call last):
Traceback (most recent call last):
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 527, in _apply_op_helper
2019-03-27 14:13:47.552658: W tensorflow/core/kernels/data/generator_dataset_op.cc:79] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
    preferred_dtype=default_dtype)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1186, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 2167, in _TensorConversionFunction
2019-03-27 14:13:47.572142: W tensorflow/core/kernels/data/generator_dataset_op.cc:79] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
2019-03-27 14:13:47.578425: W tensorflow/core/kernels/data/generator_dataset_op.cc:79] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
2019-03-27 14:13:47.593284: W tensorflow/core/kernels/data/generator_dataset_op.cc:79] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
2019-03-27 14:13:47.593964: W tensorflow/core/kernels/data/generator_dataset_op.cc:79] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
2019-03-27 14:13:47.594160: W tensorflow/core/kernels/data/generator_dataset_op.cc:79] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
2019-03-27 14:13:47.607486: W tensorflow/core/kernels/data/generator_dataset_op.cc:79] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
2019-03-27 14:13:47.608638: W tensorflow/core/kernels/data/generator_dataset_op.cc:79] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
2019-03-27 14:13:47.661584: W tensorflow/core/kernels/data/generator_dataset_op.cc:79] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 527, in _apply_op_helper
2019-03-27 14:13:47.677516: W tensorflow/core/kernels/data/generator_dataset_op.cc:79] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
Traceback (most recent call last):
Traceback (most recent call last):
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 527, in _apply_op_helper
Traceback (most recent call last):
    preferred_dtype=default_dtype)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1186, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 2167, in _TensorConversionFunction
    "of type '%s'" % (dtype.name, v.dtype.name))
ValueError: Incompatible type conversion requested to type 'float16' for variable of type 'float32_ref'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "stemdl_run.py", line 276, in <module>
    main()
  File "stemdl_run.py", line 252, in main
    FLAGS
  File "../hspace/hyperspace_launcher.py", line 60, in run_hyperspace
    random_state=777
  File "/gpfs/alpine/lrn001/proj-shared/yngtodd/src/scikit-optimize/skopt/optimizer/gp.py", line 228, in gp_minimize
    callback=callback, n_jobs=n_jobs)
  File "/gpfs/alpine/lrn001/proj-shared/yngtodd/src/scikit-optimize/skopt/optimizer/base.py", line 240, in base_minimize
    y0 = list(map(func, x0))
  File "../hspace/hyperspace_launcher.py", line 51, in <lambda>
    params
  File "../hspace/medium_objective.py", line 42, in objective
    train_loss = runtime.train(network_config, hyper_params, params, hyper_optimization=True)
  File "../stemdl/runtime.py", line 374, in train
    validate(network_config, hyper_params, params, sess, dset)
  File "../stemdl/runtime.py", line 439, in validate
    preferred_dtype=default_dtype)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1186, in internal_convert_to_tensor
    n_net.build_model()
  File "../stemdl/network.py", line 965, in build_model
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 2167, in _TensorConversionFunction
    out, kernel = self._conv(input=self.images, params=layer_params)
  File "../stemdl/network.py", line 378, in _conv
    output = tf.nn.conv2d(input, kernel, stride_shape, data_format='NCHW', padding=params['padding'])
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1951, in conv2d
    "of type '%s'" % (dtype.name, v.dtype.name))
ValueError: Incompatible type conversion requested to type 'float16' for variable of type 'float32_ref'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "stemdl_run.py", line 276, in <module>
    name=name)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1071, in conv2d
    main()
  File "stemdl_run.py", line 252, in main
    FLAGS
  File "../hspace/hyperspace_launcher.py", line 60, in run_hyperspace
    random_state=777
  File "/gpfs/alpine/lrn001/proj-shared/yngtodd/src/scikit-optimize/skopt/optimizer/gp.py", line 228, in gp_minimize
    data_format=data_format, dilations=dilations, name=name)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 563, in _apply_op_helper
    callback=callback, n_jobs=n_jobs)
  File "/gpfs/alpine/lrn001/proj-shared/yngtodd/src/scikit-optimize/skopt/optimizer/base.py", line 240, in base_minimize
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 527, in _apply_op_helper
    y0 = list(map(func, x0))
  File "../hspace/hyperspace_launcher.py", line 51, in <lambda>
    inferred_from[input_arg.type_attr]))
TypeError: Input 'filter' of 'Conv2D' Op has type float32 that does not match type float16 of argument 'input'.
    params
  File "../hspace/medium_objective.py", line 42, in objective
    train_loss = runtime.train(network_config, hyper_params, params, hyper_optimization=True)
  File "../stemdl/runtime.py", line 374, in train
    validate(network_config, hyper_params, params, sess, dset)
  File "../stemdl/runtime.py", line 439, in validate
    n_net.build_model()
  File "../stemdl/network.py", line 965, in build_model
    out, kernel = self._conv(input=self.images, params=layer_params)
  File "../stemdl/network.py", line 378, in _conv
    output = tf.nn.conv2d(input, kernel, stride_shape, data_format='NCHW', padding=params['padding'])
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1951, in conv2d
    name=name)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 563, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'filter' of 'Conv2D' Op has type float32 that does not match type float16 of argument 'input'.
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 527, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1186, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 2167, in _TensorConversionFunction
    "of type '%s'" % (dtype.name, v.dtype.name))
ValueError: Incompatible type conversion requested to type 'float16' for variable of type 'float32_ref'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "stemdl_run.py", line 276, in <module>
    main()
  File "stemdl_run.py", line 252, in main
    FLAGS
  File "../hspace/hyperspace_launcher.py", line 60, in run_hyperspace
    random_state=777
  File "/gpfs/alpine/lrn001/proj-shared/yngtodd/src/scikit-optimize/skopt/optimizer/gp.py", line 228, in gp_minimize
    callback=callback, n_jobs=n_jobs)
  File "/gpfs/alpine/lrn001/proj-shared/yngtodd/src/scikit-optimize/skopt/optimizer/base.py", line 240, in base_minimize
    y0 = list(map(func, x0))
  File "../hspace/hyperspace_launcher.py", line 51, in <lambda>
    params
  File "../hspace/medium_objective.py", line 42, in objective
    train_loss = runtime.train(network_config, hyper_params, params, hyper_optimization=True)
  File "../stemdl/runtime.py", line 374, in train
    validate(network_config, hyper_params, params, sess, dset)
  File "../stemdl/runtime.py", line 439, in validate
    n_net.build_model()
  File "../stemdl/network.py", line 965, in build_model
    out, kernel = self._conv(input=self.images, params=layer_params)
  File "../stemdl/network.py", line 378, in _conv
    output = tf.nn.conv2d(input, kernel, stride_shape, data_format='NCHW', padding=params['padding'])
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1951, in conv2d
    name=name)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 563, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'filter' of 'Conv2D' Op has type float32 that does not match type float16 of argument 'input'.
    "of type '%s'" % (dtype.name, v.dtype.name))
ValueError: Incompatible type conversion requested to type 'float16' for variable of type 'float32_ref'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "stemdl_run.py", line 276, in <module>
    main()
  File "stemdl_run.py", line 252, in main
    FLAGS
  File "../hspace/hyperspace_launcher.py", line 60, in run_hyperspace
    random_state=777
  File "/gpfs/alpine/lrn001/proj-shared/yngtodd/src/scikit-optimize/skopt/optimizer/gp.py", line 228, in gp_minimize
    callback=callback, n_jobs=n_jobs)
  File "/gpfs/alpine/lrn001/proj-shared/yngtodd/src/scikit-optimize/skopt/optimizer/base.py", line 240, in base_minimize
    y0 = list(map(func, x0))
  File "../hspace/hyperspace_launcher.py", line 51, in <lambda>
    params
  File "../hspace/medium_objective.py", line 42, in objective
    train_loss = runtime.train(network_config, hyper_params, params, hyper_optimization=True)
  File "../stemdl/runtime.py", line 374, in train
    validate(network_config, hyper_params, params, sess, dset)
  File "../stemdl/runtime.py", line 439, in validate
    n_net.build_model()
  File "../stemdl/network.py", line 965, in build_model
    out, kernel = self._conv(input=self.images, params=layer_params)
  File "../stemdl/network.py", line 378, in _conv
    output = tf.nn.conv2d(input, kernel, stride_shape, data_format='NCHW', padding=params['padding'])
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1951, in conv2d
    name=name)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 563, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'filter' of 'Conv2D' Op has type float32 that does not match type float16 of argument 'input'.
    preferred_dtype=default_dtype)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1186, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 2167, in _TensorConversionFunction
    "of type '%s'" % (dtype.name, v.dtype.name))
ValueError: Incompatible type conversion requested to type 'float16' for variable of type 'float32_ref'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "stemdl_run.py", line 276, in <module>
    main()
  File "stemdl_run.py", line 252, in main
    FLAGS
  File "../hspace/hyperspace_launcher.py", line 60, in run_hyperspace
    random_state=777
  File "/gpfs/alpine/lrn001/proj-shared/yngtodd/src/scikit-optimize/skopt/optimizer/gp.py", line 228, in gp_minimize
    callback=callback, n_jobs=n_jobs)
  File "/gpfs/alpine/lrn001/proj-shared/yngtodd/src/scikit-optimize/skopt/optimizer/base.py", line 240, in base_minimize
    y0 = list(map(func, x0))
  File "../hspace/hyperspace_launcher.py", line 51, in <lambda>
    params
  File "../hspace/medium_objective.py", line 42, in objective
    train_loss = runtime.train(network_config, hyper_params, params, hyper_optimization=True)
  File "../stemdl/runtime.py", line 374, in train
    validate(network_config, hyper_params, params, sess, dset)
  File "../stemdl/runtime.py", line 439, in validate
    n_net.build_model()
  File "../stemdl/network.py", line 965, in build_model
    out, kernel = self._conv(input=self.images, params=layer_params)
  File "../stemdl/network.py", line 378, in _conv
    output = tf.nn.conv2d(input, kernel, stride_shape, data_format='NCHW', padding=params['padding'])
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1951, in conv2d
    name=name)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 563, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'filter' of 'Conv2D' Op has type float32 that does not match type float16 of argument 'input'.
2019-03-27 14:13:47.962526: W tensorflow/core/kernels/data/generator_dataset_op.cc:79] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
2019-03-27 14:13:47.964706: W tensorflow/core/kernels/data/generator_dataset_op.cc:79] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
    preferred_dtype=default_dtype)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1186, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 2167, in _TensorConversionFunction
    "of type '%s'" % (dtype.name, v.dtype.name))
ValueError: Incompatible type conversion requested to type 'float16' for variable of type 'float32_ref'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "stemdl_run.py", line 276, in <module>
    main()
  File "stemdl_run.py", line 252, in main
    FLAGS
  File "../hspace/hyperspace_launcher.py", line 60, in run_hyperspace
    random_state=777
  File "/gpfs/alpine/lrn001/proj-shared/yngtodd/src/scikit-optimize/skopt/optimizer/gp.py", line 228, in gp_minimize
    callback=callback, n_jobs=n_jobs)
  File "/gpfs/alpine/lrn001/proj-shared/yngtodd/src/scikit-optimize/skopt/optimizer/base.py", line 240, in base_minimize
    y0 = list(map(func, x0))
  File "../hspace/hyperspace_launcher.py", line 51, in <lambda>
    params
  File "../hspace/medium_objective.py", line 42, in objective
    train_loss = runtime.train(network_config, hyper_params, params, hyper_optimization=True)
  File "../stemdl/runtime.py", line 374, in train
    validate(network_config, hyper_params, params, sess, dset)
  File "../stemdl/runtime.py", line 439, in validate
    n_net.build_model()
  File "../stemdl/network.py", line 965, in build_model
    out, kernel = self._conv(input=self.images, params=layer_params)
  File "../stemdl/network.py", line 378, in _conv
    output = tf.nn.conv2d(input, kernel, stride_shape, data_format='NCHW', padding=params['padding'])
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1951, in conv2d
    name=name)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/gpfs/alpine/proj-shared/lrn001/jqyin/native-build/latest/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 563, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'filter' of 'Conv2D' Op has type float32 that does not match type float16 of argument 'input'.
2019-03-27 14:13:47.982989: W tensorflow/core/kernels/data/generator_dataset_op.cc:79] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
2019-03-27 14:13:47.983745: W tensorflow/core/kernels/data/generator_dataset_op.cc:79] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
2019-03-27 14:13:47.993161: W tensorflow/core/kernels/data/generator_dataset_op.cc:79] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
2019-03-27 14:13:48.010869: W tensorflow/core/kernels/data/generator_dataset_op.cc:79] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
2019-03-27 14:13:48.067952: W tensorflow/core/kernels/data/generator_dataset_op.cc:79] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
2019-03-27 14:13:48.080333: W tensorflow/core/kernels/data/generator_dataset_op.cc:79] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
2019-03-27 14:13:48.088705: W tensorflow/core/kernels/data/generator_dataset_op.cc:79] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
2019-03-27 14:13:48.098249: W tensorflow/core/kernels/data/generator_dataset_op.cc:79] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
2019-03-27 14:13:48.102283: W tensorflow/core/kernels/data/generator_dataset_op.cc:79] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
2019-03-27 14:13:48.118835: W tensorflow/core/kernels/data/generator_dataset_op.cc:79] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]

------------------------------------------------------------
Sender: LSF System <lsfadmin@batch1>
Subject: Job 310444: <stemdl> in cluster <summit> Exited

Job <stemdl> was submitted from host <login1> by user <yngtodd> in cluster <summit> at Wed Mar 27 13:40:00 2019
Job was executed on host(s) <1*batch1>, in queue <batch>, as user <yngtodd> in cluster <summit> at Wed Mar 27 13:40:10 2019
                            <42*h36n09>
                            <42*h36n18>
</ccs/home/yngtodd> was used as the home directory.
</gpfs/alpine/lrn001/proj-shared/yngtodd/src/stemdl/scripts> was used as the working directory.
Started at Wed Mar 27 13:40:10 2019
Terminated at Wed Mar 27 14:13:52 2019
Results reported at Wed Mar 27 14:13:52 2019

The output (if any) is above this job summary.

